### ISSUE TITLE
Is this project currently being maintained, or under active development?

### ISSUE THREAD

**Issue by andfaulkner** [pincher-chen/3DStructGen#1]
I find this project very interesting and it seems potentially extremely useful for computational chemistry, but I notice there haven't been commits for 15 months. Is it currently under development at all? And if not, is more development planned for it in future?

**Comment by pincher-chen** [comment]
Hi，This project is still maintained. However, we end up version 1 and do not update code on this version.  The following is the details of our new version: https://matgen.nscc-gz.cn/Tools.html.

**Comment by andfaulkner** [comment]
Great, thanks for the update.

Is the source code available for version 2? I couldn't find it at the linked location - just the online demo.

**Comment by pincher-chen** [comment]
The source code is not available for version 2 now. But we will release the source soon. There are still some bugs in our current version.
